spring.application.name=campusflow


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/campusflowdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



server.shutdown=graceful

# MongoDB
spring.data.mongodb.uri=mongodb://mongo:mongo@localhost:27017/campusflowdb?authSource=admin

campusflow.jwt.secret=campusflow-secret-key-change-in-production
campusflow.jwt.expiration-ms=604800000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
