services:
  postgres:
    image: postgres:16
    container_name: campusflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: campusflowdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: campusflow-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: campusflowdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: campusflow-backend
    restart: unless-stopped
    depends_on:
      - postgres
      - mongodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/campusflowdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo@mongodb:27017/campusflowdb?authSource=admin
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: campusflow-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
  mongodb_data:
  uploads_data:
